#!/bin/bash

set -eou pipefail

echo "Checking thumper file: $1"
i=0

cat $1 |
( while IFS= read -r r
  do
    if [ "$r" != "$i" ]
    then
      echo "Fail at $1:"$[$i+1] && false
    fi
    i=$[$i+1]
  done)

echo "Success."
